# Configurações do banco de dados
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/gestor-projeto-db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: gestorProjeto
    password: gestorProjeto123
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 1
      maximum-pool-size: 12
      idle-timeout: 30000
      max-lifetime: 1800000 
      auto-commit: true
      connection-timeout: 30000
      connection-test-query: SELECT 1 
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
    database-platform: org.hibernate.dialect.MySQL8Dialect
#    hibernate:
#      ddl-auto: create

# Configurações de Porta
server:
  port: 8081

security:
  oauth2:
    resourceserver:
      jwt:
        issuer-url: http://localhost:8080/realm/configep